# market-analyzer/docker-compose.yml

services:
  db:
    image: mysql:8.0
    container_name: market_analyzer_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

  redis: # <<--- Redis 서비스 추가
    image: redis:7-alpine
    container_name: market_analyzer_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market_analyzer_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+mysqlconnector://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
      SECRET_KEY: your_super_secret_key_here
      # 외부 API 키 환경 변수 추가
      ALPHA_VANTAGE_API_KEY_1: ${ALPHA_VANTAGE_API_KEY_1}
      FMP_API_KEY: ${FMP_API_KEY}
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      redis: # <<--- redis 서비스에 의존성 추가
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./.env:/app/.env  # 이 부분이 중요

    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: market_analyzer_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/app
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: market_analyzer_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 2048M # 이 줄을 주석 처리하거나 삭제합니다.
    ports:
      - "8081:80" # 포트 충돌을 피하기 위해 8081로 변경 (기존 8080 사용 시)
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
