// Centralized exports for all hooks
export * from './useAssets'
export * from './useRealtime'
export * from './useCrypto'
export * from './useIntradayApi'
export * from './useSocket'
export * from './useGoBack'
export * from './useModal'
export * from './useAssetOverview'
export * from './useOnchain'
export * from './useBlog'
export * from './usePosts'

// Re-export commonly used hooks with shorter names
export { useOhlcvData as useOhlcv } from './useAssets'
export { useIntradayOhlcv as useIntraday } from './useRealtime'
export { useAssetTypes as useTypes } from './useAssets'
export { useAssets as useAssetsList } from './useAssets'
export { useAssetOverview as useOverview } from './useAssetOverview'
export { useOnchain as useOnchainData } from './useOnchain'
export { useOnchainMetrics as useMetrics } from './useOnchain'
