-- onchain_metrics_info 테이블 데이터 업데이트 스크립트
-- FireMarkets 프로젝트용

-- 기존 데이터 삭제 (필요시)
-- DELETE FROM onchain_metrics_info;

-- 새로운 데이터 삽입
INSERT INTO onchain_metrics_info (metric_id, name, description, category, interpretations, chart_title, loading_text, status, data_count, current_range, last_update, is_enabled, created_at, updated_at) VALUES
('aviv', 'AVIV Ratio (Active Value to Investor Value)', 'Represents the ratio of value between short-term traders (Active Value) and long-term holders (Investor Value). Compares the relative value between these two groups.', 'Market', '{"low": "Very Low Ratio: May indicate that the market is in a deep slump.", "weak": "Ratio Falling: The value of long-term holders is relatively higher, often seen during market slumps or accumulation phases.", "strong": "Ratio Rising: The value of short-term trader activity is increasing relative to long-term holders, which can be a sign of an overheating market.", "neutral": "Can help identify inflection points in the market cycle.", "moderate": "Stable Ratio: Activity between short-term and long-term investors is balanced."}', 'Bitcoin Price vs. AVIV Ratio', 'Loading AVIV Ratio data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('cdd_90dma', 'CDD (90-Day Moving Average)', 'The 90-day moving average of Coin Days Destroyed. The value rises when long-term holders move (sell) their coins, making it useful for tracking their behavior.', 'Market', '{"low": "Very Low CDD: The market is in a slump, or there is very little activity from long-term holders.", "weak": "CDD Falling: Long-term holders are holding onto their coins (HODLing), indicating strong conviction in the market.", "strong": "CDD Rising: Long-term holders are moving a large volume of coins, which could be a sign of profit-taking or a market top.", "neutral": "Low and Stable CDD: The market is in an accumulation phase, or there is no selling pressure from long-term holders.", "moderate": "CDD Stable: The activity of long-term holders is at a normal level."}', 'Bitcoin Price vs. CDD (90-Day MA)', 'Loading CDD (90-Day MA) data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('difficulty', 'Difficulty', 'A measure of how difficult it is to find a new block. It adjusts approximately every two weeks based on the network''s hash rate.', 'Mining', '{"low": "Sharp Decline: Suggests a large-scale exodus of miners, which can be a negative signal for the market.", "weak": "Difficulty Falling: Miners are leaving the network (a result of falling hash rate), indicating a slowdown in network activity.", "strong": "Difficulty Rising: More miners are competing (a result of rising hash rate), which is a sign of a healthy network.", "neutral": "Lagging Indicator: Generally follows changes in hash rate and tends to lag price movements.", "moderate": "Difficulty Stable: Miner activity is maintaining a stable level."}', 'Bitcoin Price vs. Difficulty', 'Loading Difficulty data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('etf_btc_flow', 'ETF BTC Flow', 'The daily net amount of Bitcoin flowing in or out of spot ETFs. Shows short-term institutional buying/selling pressure.', 'Institutional', '{"low": "Consistent Net Outflow (Negative): Indicates strong short-term selling pressure and can be a cause of price decline.", "weak": "Small Net Outflow: Indicates weak short-term selling pressure.", "strong": "Consistent Net Inflow (Positive): Indicates strong short-term buying pressure.", "neutral": "Near-Zero Value: Buying and selling pressures are balanced.", "moderate": "Small Net Inflow: Buying pressure is being maintained."}', 'Bitcoin Price vs. ETF BTC Flow', 'Loading ETF BTC Flow data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('etf_btc_total', 'ETF BTC Total', 'The total amount of Bitcoin held by all spot Bitcoin ETF products worldwide. An important indicator of institutional demand.', 'Institutional', '{"low": "Sharp Decrease: Signifies a large-scale exit of institutional investors, which can have a significant negative market impact.", "weak": "Total Holdings Decreasing: Institutional investors are withdrawing funds, acting as potential selling pressure.", "strong": "Total Holdings Increasing: Institutional funds are continuously flowing in, acting as strong buying pressure.", "neutral": "Slowing Volatility: Indicates neutral interest from institutional investors.", "moderate": "Total Holdings Stable: Institutional inflow is slowing down or has stabilized."}', 'Bitcoin Price vs. ETF BTC Total', 'Loading ETF BTC Total data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('hashrate', 'Hash Rate', 'The total combined computational power being used to mine and process transactions on the Bitcoin network. A key indicator of network security and health.', 'Mining', '{"low": "Sharp Decline: May indicate miner capitulation, which can have a negative impact on the market.", "weak": "Hash Rate Falling: Miners are shutting down due to profitability issues or uncertainty, which can weaken network security.", "strong": "Hash Rate Rising: Network security is strengthening, and miners are investing more resources, indicating a positive long-term outlook.", "neutral": "Independent Moves: Can move independently of price in the short term but reflects long-term network fundamentals.", "moderate": "Hash Rate Stable: The network is operating stably."}', 'Bitcoin Price vs. Hash Rate', 'Loading Hash Rate data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('hodl_waves_supply', 'HODL Waves', 'A visualization of the age distribution of Bitcoin. It helps gauge market sentiment by showing changes in the ratio of long-term holders to short-term traders.', 'Market', '{"low": "A significant increase in the proportion of coins held for over a year increases the likelihood of a supply shock.", "weak": "Increase in Cool Colors (Long-term Holders): Coins are moving to long-term holders, a trend seen at market bottoms and during accumulation phases.", "strong": "Increase in Warm Colors (Short-term Holders): New participants are entering, a trend often seen near market tops.", "neutral": "The color distribution shows cyclical patterns that follow the market cycle.", "moderate": "Even Color Distribution: Indicates a stable market."}', 'Bitcoin Price vs. HODL Waves', 'Loading HODL Waves data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('miner_reserves', 'Miner Reserves', 'The total amount of bitcoin held in all known miner wallets. Used to gauge potential selling pressure from miners.', 'Mining', '{"low": "Sharp Decrease: Miners may be conducting large-scale selling to cover operational costs or realize profits.", "weak": "Reserves Decreasing: Miners are sending bitcoin to exchanges to sell, which can act as potential sell pressure.", "strong": "Reserves Increasing: Miners are accumulating instead of selling, suggesting they anticipate future price increases.", "neutral": "No significant change: The mining market is in a stable state.", "moderate": "Reserves Stable: Miners are in a holding pattern, observing the current market conditions."}', 'Bitcoin Price vs. Miner Reserves', 'Loading Miner Reserves data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('mvrv_z_score', 'MVRV Z-Score (Market Value to Realized Value Z-Score)', 'Measures how over/undervalued the current market value is compared to the realized value (the average price when coins last moved). Used to identify market tops and bottoms.', 'Market', '{"low": "Below -0.5 (Dark Blue Zone): Market is extremely undervalued, high probability of forming a historical bottom. (Buy Signal)", "weak": "0-3 (Green Zone): Market is in a healthy state, finding its value.", "strong": "Above 7 (Red Zone): Market is extremely overheated, high probability of forming a historical top. (Sell Signal)", "neutral": "-0.5-0 (Blue Zone): Market is beginning to be undervalued, accumulation can be considered.", "moderate": "3-7 (Orange Zone): Market is overvalued, caution is advised."}', 'Bitcoin Price vs. MVRV Z-Score', 'Loading MVRV Z-Score data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('nrpl_btc', 'NRPL (Net Realized Profit/Loss)', 'The net value of all on-chain transactions for a day, calculated as total profit minus total loss. It shows the actual scale of profit/loss in the market.', 'Market', '{"low": "Large Negative Value: Large-scale loss realization (capitulation) is occurring, a trend often seen near market bottoms.", "weak": "Near-Zero Value: Profit-taking and loss-taking are balanced.", "strong": "High Positive Value: Large-scale profit-taking is occurring, a trend often seen near market tops.", "neutral": "Positive values mean profit-taking is dominant; negative values mean loss-taking is dominant.", "moderate": "Low Positive Value: Healthy profit-taking is occurring in a bull market."}', 'Bitcoin Price vs. NRPL', 'Loading NRPL data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('nupl', 'NUPL (Net Unrealized Profit/Loss)', 'Represents the total unrealized profit/loss of all coins that have not yet been sold. It is useful for measuring the overall greed and fear in the market.', 'Market', '{"low": "Below 0 (Fear/Capitulation): Extreme fear, potential for a market bottom. (Buy Signal)", "weak": "0.25-0.5 (Optimism): Indicates a healthy uptrend.", "strong": "Above 0.75 (Euphoria): Extreme greed, potential for a market top. (Sell Signal)", "neutral": "0-0.25 (Hope/Anxiety): Market is in a recovery phase or experiencing anxiety after a decline.", "moderate": "0.5-0.75 (Greed): Market is overheated, and investor profit expectations are high."}', 'Bitcoin Price vs. NUPL', 'Loading NUPL data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('open_interest_futures', 'Open Interest (Futures)', 'The total number of outstanding futures contracts that have not been settled. Used to gauge the level of leverage and potential volatility in the market.', 'Derivatives', '{"low": "Rapid Decrease in Open Interest: A large-scale position liquidation has occurred, often seen after a major volatility event.", "weak": "Decrease in Open Interest: Traders are closing their positions, suggesting waning market interest.", "strong": "Rapid Increase in Open Interest: Leverage is building up in the market, which could lead to high volatility (potential for long/short squeezes).", "neutral": "Stable Level: The derivatives market is in a stable state.", "moderate": "Gradual Increase in Open Interest: Indicates growing interest in the market."}', 'Bitcoin Price vs. Open Interest (Futures)', 'Loading Open Interest (Futures) data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('realized_cap', 'Realized Cap', 'The value of all bitcoins at the price they were last moved on-chain. It represents the actual capital inflow into the network, partially excluding speculative value.', 'Market', '{"low": "Sharp Decline: Can indicate panic selling during a bear market.", "weak": "Realized Cap Falling: Capital is leaving the network as participants sell at an average loss.", "strong": "Realized Cap Rising: New capital is steadily flowing into the network, a healthy long-term signal.", "neutral": "Used to judge over/undervaluation by comparing it with Market Cap (MVRV = Market Cap / Realized Cap).", "moderate": "Realized Cap Stable: Capital inflow is stable or slowing down."}', 'Bitcoin Price vs. Realized Cap', 'Loading Realized Cap data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('realized_price', 'Realized Price', 'The average price of all bitcoins at the time they were last moved on-chain. It can be considered the average cost basis for long-term investors.', 'Price', '{"low": "Large gap: The market may be overheated (Market >> Realized) or in a deep slump (Market << Realized).", "weak": "Market Price < Realized Price: The market is generally in a state of loss, indicating a bear market and putting psychological pressure on long-term holders.", "strong": "Market Price > Realized Price: The market is generally in a state of profit, indicating a bull market.", "neutral": "Similar levels: Indicates neutral sentiment or an approaching inflection point.", "moderate": "Market Price ≈ Realized Price: The market is at a breakeven point, which can act as a crucial support or resistance level."}', 'Bitcoin Price vs. Realized Price', 'Loading Realized Price data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('sopr', 'SOPR (Spent Output Profit Ratio)', 'Indicates whether sold coins were, on average, sold at a profit or a loss. A value of 1 is the breakeven point. It helps gauge overall profit-taking sentiment.', 'Market', '{"low": "Below 0.98: Participants are, on average, selling at a loss, which can be a sign of capitulation.", "weak": "1.0-1.02: Slight profit-taking is occurring, can act as support in a bull market.", "strong": "Above 1.05: Significant profit-taking is occurring, potential sell pressure is high.", "neutral": "0.98-1.0: Breakeven level, market direction is ambiguous.", "moderate": "1.02-1.05: Market participants are realizing profits."}', 'Bitcoin Price vs. SOPR', 'Loading SOPR data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('thermo_cap', 'Thermo Cap', 'Represents the cumulative security spend by miners (total mining revenue). It shows the economic foundation of the network.', 'Mining', '{"low": "When the price approaches Thermo Cap, it can be considered a potential buying opportunity.", "weak": "The growth rate of Thermo Cap reflects the growth rate of the network.", "strong": "Thermo Cap consistently trends upward, representing the cumulative energy invested in the network.", "neutral": "It is sometimes interpreted as the minimum value floor for the network.", "moderate": "It is rare for the price to fall below Thermo Cap, which would be considered an extremely undervalued state."}', 'Bitcoin Price vs. Thermo Cap', 'Loading Thermo Cap data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30'),

('true_market_mean', 'True Market Mean', 'An average price calculated from various Bitcoin valuation models. It can be used to estimate the intrinsic value of the market.', 'Price', '{"low": "A larger gap between the two prices may indicate greater market inefficiency.", "weak": "Market Price < Mean Price: The market may be undervalued compared to its intrinsic value, potentially an attractive buying zone.", "strong": "Market Price > Mean Price: The market may be overvalued compared to its intrinsic value.", "neutral": "The relationship between the two prices can help determine the degree of market overheating or slump.", "moderate": "Market Price ≈ Mean Price: The market price is close to its intrinsic value."}', 'Bitcoin Price vs. True Market Mean', 'Loading True Market Mean data...', 'active', 0, NULL, NULL, 1, '2025-08-04 04:36:30', '2025-08-04 04:36:30')

-- 중복 키 오류 방지를 위한 ON CONFLICT 처리
ON CONFLICT (metric_id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    interpretations = EXCLUDED.interpretations,
    chart_title = EXCLUDED.chart_title,
    loading_text = EXCLUDED.loading_text,
    status = EXCLUDED.status,
    is_enabled = EXCLUDED.is_enabled,
    updated_at = CURRENT_TIMESTAMP;

-- 완료 메시지
DO $$
BEGIN
    RAISE NOTICE 'OnChain Metrics Info 업데이트 완료: 모든 메트릭 데이터가 업데이트되었습니다.';
END $$;
