"""add_economic_fred_models

Revision ID: b29565f1f5cc
Revises: 8bed180f2562
Create Date: 2026-01-29 11:01:46.726806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b29565f1f5cc'
down_revision: Union[str, None] = '8bed180f2562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_info')
    op.drop_table('apscheduler_jobs')
    op.drop_table('websocket_orchestrator_logs')
    op.drop_table('blog_post_tags')
    op.drop_index('ux_menus_path', table_name='menus')
    op.drop_table('menus')
    op.alter_column('api_call_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('api_call_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_api_call_logs_api_name'), 'api_call_logs', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_call_logs_asset_ticker'), 'api_call_logs', ['asset_ticker'], unique=False)
    op.create_index(op.f('ix_api_call_logs_created_at'), 'api_call_logs', ['created_at'], unique=False)
    op.alter_column('app_configurations', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('app_configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_app_configurations_config_key'), 'app_configurations', ['config_key'], unique=True)
    op.create_index(op.f('ix_asset_types_asset_type_id'), 'asset_types', ['asset_type_id'], unique=False)
    op.create_unique_constraint(None, 'asset_types', ['type_name'])
    op.alter_column('assets', 'collection_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('assets', 'last_collections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('assets', 'data_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'fmp'::character varying"))
    op.drop_index('idx_asset_basic_ticker', table_name='assets', postgresql_where='(is_active = true)')
    op.drop_index('idx_asset_basic_type', table_name='assets', postgresql_where='(is_active = true)')
    op.drop_index('idx_assets_asset_type_id', table_name='assets')
    op.drop_constraint('uq_assets_ticker', 'assets', type_='unique')
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.drop_constraint('fk_assets_asset_type', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'asset_types', ['asset_type_id'], ['asset_type_id'])
    op.alter_column('bond_market_data', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_foreign_key(None, 'bond_market_data', 'asset_types', ['asset_type_id'], ['asset_type_id'])
    op.alter_column('crypto_data', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crypto_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_crypto_data_asset', table_name='crypto_data')
    op.drop_index('idx_crypto_data_asset_id', table_name='crypto_data')
    op.drop_constraint('unique_crypto_data_asset_id', 'crypto_data', type_='unique')
    op.create_index(op.f('ix_crypto_data_asset_id'), 'crypto_data', ['asset_id'], unique=True)
    op.create_index(op.f('ix_crypto_data_id'), 'crypto_data', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_data_symbol'), 'crypto_data', ['symbol'], unique=False)
    op.create_foreign_key(None, 'crypto_data', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('crypto_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crypto_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ux_crypto_metrics_asset_ts', table_name='crypto_metrics')
    op.create_unique_constraint('ux_crypto_metrics_asset_ts', 'crypto_metrics', ['asset_id', 'timestamp_utc'])
    op.create_index(op.f('ix_crypto_metrics_asset_id'), 'crypto_metrics', ['asset_id'], unique=False)
    op.create_index(op.f('ix_crypto_metrics_timestamp_utc'), 'crypto_metrics', ['timestamp_utc'], unique=False)
    op.create_foreign_key(None, 'crypto_metrics', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('economic_indicators', 'indicator_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('economic_indicators', 'indicator_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('economic_indicators', 'value',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.alter_column('economic_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('economic_indicators', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_economic_indicators_indicator_code'), 'economic_indicators', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_economic_indicators_timestamp'), 'economic_indicators', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_economic_indicator_code_timestamp', 'economic_indicators', ['indicator_code', 'timestamp'])
    op.alter_column('etf_info', 'snapshot_date',
               existing_type=sa.DATE(),
               comment='Information reference date (stores the latest information)',
               existing_nullable=False)
    op.alter_column('etf_info', 'net_assets',
               existing_type=sa.NUMERIC(precision=22, scale=0),
               comment='Net Assets',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'net_expense_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Net Expense Ratio',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'portfolio_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Portfolio Turnover Rate',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'dividend_yield',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Dividend Yield',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'inception_date',
               existing_type=sa.DATE(),
               comment='Inception Date',
               existing_nullable=True)
    op.alter_column('etf_info', 'leveraged',
               existing_type=sa.BOOLEAN(),
               comment='Leveraged status',
               existing_nullable=True)
    op.alter_column('etf_info', 'sectors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='ETF 섹터별 비중 정보',
               existing_nullable=True)
    op.alter_column('etf_info', 'holdings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='ETF 보유 종목 정보',
               existing_nullable=True)
    op.alter_column('etf_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('etf_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_etf_info_asset', table_name='etf_info')
    op.drop_index('idx_etf_info_asset_id', table_name='etf_info')
    op.drop_constraint('unique_etf_info_asset_id', 'etf_info', type_='unique')
    op.create_index(op.f('ix_etf_info_asset_id'), 'etf_info', ['asset_id'], unique=True)
    op.create_index(op.f('ix_etf_info_etf_info_id'), 'etf_info', ['etf_info_id'], unique=False)
    op.create_foreign_key(None, 'etf_info', 'assets', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.add_column('index_infos', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('index_infos', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_index_infos_index_info_id'), 'index_infos', ['index_info_id'], unique=False)
    op.create_foreign_key(None, 'index_infos', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('m2_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('m2_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_m2_data_timestamp_utc'), 'm2_data', ['timestamp_utc'], unique=False)
    op.create_unique_constraint('uq_m2_data_timestamp', 'm2_data', ['timestamp_utc'])
    op.alter_column('ohlcv_day_data', 'data_interval',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ohlcv_day_data', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=30, scale=10),
               nullable=False)
    op.alter_column('ohlcv_day_data', 'change_percent',
               existing_type=sa.NUMERIC(precision=9, scale=4),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=True)
    op.drop_index('idx_ohlcv_asset_timestamp_desc', table_name='ohlcv_day_data')
    op.drop_index('idx_ohlcv_day_asset', table_name='ohlcv_day_data')
    op.drop_index('idx_ohlcv_day_asset_date', table_name='ohlcv_day_data')
    op.drop_index('idx_ohlcv_day_timestamp', table_name='ohlcv_day_data')
    op.drop_index('uq_ohlcv_day_asset_time', table_name='ohlcv_day_data')
    op.drop_constraint('uq_ohlcv_day_data', 'ohlcv_day_data', type_='unique')
    op.create_index(op.f('ix_ohlcv_day_data_asset_id'), 'ohlcv_day_data', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_day_data_ohlcv_id'), 'ohlcv_day_data', ['ohlcv_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_day_data_timestamp_utc'), 'ohlcv_day_data', ['timestamp_utc'], unique=False)
    op.drop_column('ohlcv_day_data', 'adjusted_close')
    op.drop_column('ohlcv_day_data', 'updated_at')
    op.alter_column('ohlcv_intraday_data', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=30, scale=10),
               nullable=False)
    op.alter_column('ohlcv_intraday_data', 'change_percent',
               existing_type=sa.NUMERIC(precision=9, scale=4),
               type_=sa.DECIMAL(precision=10, scale=4),
               existing_nullable=True)
    op.drop_index('idx_ohlcv_intraday_asset', table_name='ohlcv_intraday_data')
    op.drop_index('idx_ohlcv_intraday_asset_date', table_name='ohlcv_intraday_data')
    op.drop_index('idx_ohlcv_intraday_timestamp', table_name='ohlcv_intraday_data')
    op.drop_constraint('uq_ohlcv_intraday_data', 'ohlcv_intraday_data', type_='unique')
    op.create_index(op.f('ix_ohlcv_intraday_data_asset_id'), 'ohlcv_intraday_data', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_intraday_data_ohlcv_id'), 'ohlcv_intraday_data', ['ohlcv_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_intraday_data_timestamp_utc'), 'ohlcv_intraday_data', ['timestamp_utc'], unique=False)
    op.drop_column('ohlcv_intraday_data', 'adjusted_close')
    op.drop_column('ohlcv_intraday_data', 'updated_at')
    op.alter_column('onchain_metrics_info', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('onchain_metrics_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('onchain_metrics_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_blog_categories_parent', table_name='post_categories')
    op.drop_index('idx_blog_categories_slug', table_name='post_categories')
    op.alter_column('post_charts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_charts', 'symbols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('post_charts', 'indicators',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_blog_charts_blog_id', table_name='post_charts')
    op.drop_index('idx_blog_charts_symbol', table_name='post_charts')
    op.drop_constraint('blog_charts_blog_id_fkey', 'post_charts', type_='foreignkey')
    op.alter_column('post_comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_blog_comments_blog_id', table_name='post_comments')
    op.drop_index('idx_blog_comments_created_at', table_name='post_comments')
    op.drop_index('idx_blog_comments_status', table_name='post_comments')
    op.drop_constraint('blog_comments_blog_id_fkey', 'post_comments', type_='foreignkey')
    op.alter_column('post_products', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_products', 'product_symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('blog_products_blog_id_product_symbol_key', 'post_products', type_='unique')
    op.drop_index('idx_blog_products_blog_id', table_name='post_products')
    op.drop_index('idx_blog_products_symbol', table_name='post_products')
    op.drop_constraint('blog_products_blog_id_fkey', 'post_products', type_='foreignkey')
    op.drop_index('idx_blog_tags_slug', table_name='post_tags')
    op.drop_index('idx_blog_tags_usage', table_name='post_tags')
    op.alter_column('posts', 'excerpt',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posts', 'meta_title',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posts', 'meta_description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posts', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posts', 'post_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'post'::character varying"))
    op.alter_column('posts', 'menu_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'ping_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('posts', 'post_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_blogs_asset_id', table_name='posts')
    op.drop_index('idx_blogs_author', table_name='posts')
    op.drop_index('idx_blogs_category', table_name='posts')
    op.drop_index('idx_blogs_post_type', table_name='posts')
    op.drop_index('idx_blogs_published_at', table_name='posts')
    op.drop_index('idx_blogs_sync_status', table_name='posts')
    op.drop_index('idx_posts_asset_id_post_type', table_name='posts', postgresql_where="((asset_id IS NOT NULL) AND ((post_type)::text = 'assets'::text))")
    op.drop_index('idx_posts_asset_type_id', table_name='posts')
    op.drop_index('idx_posts_created_at', table_name='posts')
    op.drop_index('idx_posts_post_info', table_name='posts', postgresql_using='gin')
    op.drop_index('idx_posts_slug', table_name='posts')
    op.drop_index('idx_posts_status', table_name='posts')
    op.drop_index('ux_posts_asset_unique_asset_published', table_name='posts', postgresql_where="(((post_type)::text = 'assets'::text) AND (published_at IS NOT NULL))")
    op.drop_constraint('blogs_post_parent_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('blogs_asset_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'visibility')
    op.drop_column('posts', 'permissions')
    op.drop_column('posts', 'shared_with')
    op.alter_column('realtime_quotes', 'volume',
               existing_type=sa.NUMERIC(precision=30, scale=8),
               type_=sa.DECIMAL(precision=18, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('realtime_quotes', 'change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=9, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('realtime_quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('unique_asset_id', 'realtime_quotes', type_='unique')
    op.create_index(op.f('ix_realtime_quotes_asset_id'), 'realtime_quotes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_realtime_quotes_timestamp_utc'), 'realtime_quotes', ['timestamp_utc'], unique=False)
    op.create_foreign_key(None, 'realtime_quotes', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('realtime_quotes_time_delay', 'volume',
               existing_type=sa.NUMERIC(precision=30, scale=8),
               type_=sa.DECIMAL(precision=18, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('realtime_quotes_time_delay', 'change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=9, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('realtime_quotes_time_delay', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_rt_delay_asset_time', table_name='realtime_quotes_time_delay')
    op.drop_constraint('unique_asset_time_source', 'realtime_quotes_time_delay', type_='unique')
    op.drop_index('uq_rt_delay', table_name='realtime_quotes_time_delay')
    op.create_index(op.f('ix_realtime_quotes_time_delay_asset_id'), 'realtime_quotes_time_delay', ['asset_id'], unique=False)
    op.create_index(op.f('ix_realtime_quotes_time_delay_timestamp_utc'), 'realtime_quotes_time_delay', ['timestamp_utc'], unique=False)
    op.create_unique_constraint('uq_realtime_delay_asset_ts', 'realtime_quotes_time_delay', ['asset_id', 'timestamp_utc'])
    op.create_foreign_key(None, 'realtime_quotes_time_delay', 'assets', ['asset_id'], ['asset_id'])
    op.create_index(op.f('ix_scheduler_logs_job_name'), 'scheduler_logs', ['job_name'], unique=False)
    op.create_index(op.f('ix_scheduler_logs_status'), 'scheduler_logs', ['status'], unique=False)
    op.alter_column('sparkline_data', 'price_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_sparkline_data_asset_type'), 'sparkline_data', ['asset_type'], unique=False)
    op.create_index(op.f('ix_sparkline_data_ticker'), 'sparkline_data', ['ticker'], unique=False)
    op.drop_column('sparkline_data', 'data_source')
    op.drop_column('sparkline_data', 'fetched_at')
    op.drop_column('sparkline_data', 'currency')
    op.alter_column('stock_analyst_estimates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('unique_stock_analyst_estimates_asset_id', 'stock_analyst_estimates', type_='unique')
    op.drop_index('ux_stock_analyst_estimates_asset_id', table_name='stock_analyst_estimates')
    op.create_index(op.f('ix_stock_analyst_estimates_estimate_id'), 'stock_analyst_estimates', ['estimate_id'], unique=False)
    op.create_foreign_key(None, 'stock_analyst_estimates', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('stock_financials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_stock_financials_asset', table_name='stock_financials')
    op.drop_constraint('unique_stock_financials_asset_id', 'stock_financials', type_='unique')
    op.create_index(op.f('ix_stock_financials_financial_id'), 'stock_financials', ['financial_id'], unique=False)
    op.create_foreign_key(None, 'stock_financials', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('stock_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_stock_profiles_asset', table_name='stock_profiles')
    op.drop_index('idx_stock_profiles_asset_id', table_name='stock_profiles')
    op.create_index(op.f('ix_stock_profiles_profile_id'), 'stock_profiles', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'stock_profiles', 'assets', ['asset_id'], ['asset_id'])
    op.add_column('technical_indicators', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('technical_indicators', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('technical_indicators', sa.Column('period', sa.Integer(), nullable=True))
    op.add_column('technical_indicators', sa.Column('indicator_metadata', sa.JSON(), nullable=True))
    op.alter_column('technical_indicators', 'value',
               existing_type=sa.NUMERIC(precision=24, scale=10),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint('unique_technical_indicators_asset_id', 'technical_indicators', type_='unique')
    op.create_index(op.f('ix_technical_indicators_asset_id'), 'technical_indicators', ['asset_id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_indicator_type'), 'technical_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_technical_indicators_timestamp'), 'technical_indicators', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'technical_indicators', 'assets', ['asset_id'], ['asset_id'])
    op.drop_column('technical_indicators', 'value_3')
    op.drop_column('technical_indicators', 'value_2')
    op.drop_column('technical_indicators', 'timestamp_utc')
    op.drop_column('technical_indicators', 'data_interval')
    op.drop_column('technical_indicators', 'updated_at')
    op.drop_column('technical_indicators', 'indicator_data_id')
    op.drop_column('technical_indicators', 'created_at')
    op.drop_column('technical_indicators', 'indicator_period')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_unique', 'users', type_='unique')
    op.drop_constraint('users_username_unique', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('unique_ranking', 'world_assets_ranking', type_='unique')
    op.create_foreign_key(None, 'world_assets_ranking', 'assets', ['asset_id'], ['asset_id'])
    op.create_foreign_key(None, 'world_assets_ranking', 'asset_types', ['asset_type_id'], ['asset_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'world_assets_ranking', type_='foreignkey')
    op.drop_constraint(None, 'world_assets_ranking', type_='foreignkey')
    op.create_unique_constraint('unique_ranking', 'world_assets_ranking', ['ranking_date', 'ticker', 'data_source'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_unique', 'users', ['username'])
    op.create_unique_constraint('users_email_unique', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('technical_indicators', sa.Column('indicator_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('technical_indicators', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('technical_indicators', sa.Column('indicator_data_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('technical_indicators', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('technical_indicators', sa.Column('data_interval', sa.VARCHAR(length=10), server_default=sa.text("'1d'::character varying"), autoincrement=False, nullable=False))
    op.add_column('technical_indicators', sa.Column('timestamp_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('technical_indicators', sa.Column('value_2', sa.NUMERIC(precision=24, scale=10), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True))
    op.add_column('technical_indicators', sa.Column('value_3', sa.NUMERIC(precision=24, scale=10), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'technical_indicators', type_='foreignkey')
    op.drop_index(op.f('ix_technical_indicators_timestamp'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_indicator_type'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_asset_id'), table_name='technical_indicators')
    op.create_unique_constraint('unique_technical_indicators_asset_id', 'technical_indicators', ['asset_id'])
    op.alter_column('technical_indicators', 'value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=24, scale=10),
               existing_nullable=False)
    op.drop_column('technical_indicators', 'indicator_metadata')
    op.drop_column('technical_indicators', 'period')
    op.drop_column('technical_indicators', 'timestamp')
    op.drop_column('technical_indicators', 'id')
    op.drop_constraint(None, 'stock_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_stock_profiles_profile_id'), table_name='stock_profiles')
    op.create_index('idx_stock_profiles_asset_id', 'stock_profiles', ['asset_id'], unique=False)
    op.create_index('idx_stock_profiles_asset', 'stock_profiles', ['asset_id'], unique=False)
    op.alter_column('stock_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'stock_financials', type_='foreignkey')
    op.drop_index(op.f('ix_stock_financials_financial_id'), table_name='stock_financials')
    op.create_unique_constraint('unique_stock_financials_asset_id', 'stock_financials', ['asset_id'])
    op.create_index('idx_stock_financials_asset', 'stock_financials', ['asset_id'], unique=False)
    op.alter_column('stock_financials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'stock_analyst_estimates', type_='foreignkey')
    op.drop_index(op.f('ix_stock_analyst_estimates_estimate_id'), table_name='stock_analyst_estimates')
    op.create_index('ux_stock_analyst_estimates_asset_id', 'stock_analyst_estimates', ['asset_id'], unique=False)
    op.create_unique_constraint('unique_stock_analyst_estimates_asset_id', 'stock_analyst_estimates', ['asset_id'])
    op.alter_column('stock_analyst_estimates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('sparkline_data', sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True))
    op.add_column('sparkline_data', sa.Column('fetched_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('sparkline_data', sa.Column('data_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sparkline_data_ticker'), table_name='sparkline_data')
    op.drop_index(op.f('ix_sparkline_data_asset_type'), table_name='sparkline_data')
    op.alter_column('sparkline_data', 'price_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_scheduler_logs_status'), table_name='scheduler_logs')
    op.drop_index(op.f('ix_scheduler_logs_job_name'), table_name='scheduler_logs')
    op.drop_constraint(None, 'realtime_quotes_time_delay', type_='foreignkey')
    op.drop_constraint('uq_realtime_delay_asset_ts', 'realtime_quotes_time_delay', type_='unique')
    op.drop_index(op.f('ix_realtime_quotes_time_delay_timestamp_utc'), table_name='realtime_quotes_time_delay')
    op.drop_index(op.f('ix_realtime_quotes_time_delay_asset_id'), table_name='realtime_quotes_time_delay')
    op.create_index('uq_rt_delay', 'realtime_quotes_time_delay', ['asset_id', 'timestamp_utc', 'data_source', 'data_interval'], unique=False)
    op.create_unique_constraint('unique_asset_time_source', 'realtime_quotes_time_delay', ['asset_id', 'timestamp_utc', 'data_source'])
    op.create_index('ix_rt_delay_asset_time', 'realtime_quotes_time_delay', ['asset_id', 'timestamp_utc'], unique=False)
    op.alter_column('realtime_quotes_time_delay', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('realtime_quotes_time_delay', 'change_percent',
               existing_type=sa.DECIMAL(precision=9, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('realtime_quotes_time_delay', 'volume',
               existing_type=sa.DECIMAL(precision=18, scale=8),
               type_=sa.NUMERIC(precision=30, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.drop_constraint(None, 'realtime_quotes', type_='foreignkey')
    op.drop_index(op.f('ix_realtime_quotes_timestamp_utc'), table_name='realtime_quotes')
    op.drop_index(op.f('ix_realtime_quotes_asset_id'), table_name='realtime_quotes')
    op.create_unique_constraint('unique_asset_id', 'realtime_quotes', ['asset_id'])
    op.alter_column('realtime_quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('realtime_quotes', 'change_percent',
               existing_type=sa.DECIMAL(precision=9, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('realtime_quotes', 'volume',
               existing_type=sa.DECIMAL(precision=18, scale=8),
               type_=sa.NUMERIC(precision=30, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.add_column('posts', sa.Column('shared_with', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'private'::character varying"), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_asset_id_fkey', 'posts', 'assets', ['asset_id'], ['asset_id'], ondelete='SET NULL')
    op.create_foreign_key('blogs_post_parent_fkey', 'posts', 'posts', ['post_parent'], ['id'], ondelete='SET NULL')
    op.create_index('ux_posts_asset_unique_asset_published', 'posts', ['asset_id'], unique=False, postgresql_where="(((post_type)::text = 'assets'::text) AND (published_at IS NOT NULL))")
    op.create_index('idx_posts_status', 'posts', ['status'], unique=False)
    op.create_index('idx_posts_slug', 'posts', ['slug'], unique=False)
    op.create_index('idx_posts_post_info', 'posts', ['post_info'], unique=False, postgresql_using='gin')
    op.create_index('idx_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_posts_asset_type_id', 'posts', ['asset_type_id'], unique=False)
    op.create_index('idx_posts_asset_id_post_type', 'posts', ['asset_id', 'post_type'], unique=False, postgresql_where="((asset_id IS NOT NULL) AND ((post_type)::text = 'assets'::text))")
    op.create_index('idx_blogs_sync_status', 'posts', ['sync_status'], unique=False)
    op.create_index('idx_blogs_published_at', 'posts', [sa.text('published_at DESC')], unique=False)
    op.create_index('idx_blogs_post_type', 'posts', ['post_type'], unique=False)
    op.create_index('idx_blogs_category', 'posts', ['category_id'], unique=False)
    op.create_index('idx_blogs_author', 'posts', ['author_id'], unique=False)
    op.create_index('idx_blogs_asset_id', 'posts', ['asset_id'], unique=False)
    op.alter_column('posts', 'post_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'ping_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('posts', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'menu_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'post_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'post'::character varying"))
    op.alter_column('posts', 'keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'meta_description',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'meta_title',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'excerpt',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_blog_tags_usage', 'post_tags', [sa.text('usage_count DESC')], unique=False)
    op.create_index('idx_blog_tags_slug', 'post_tags', ['slug'], unique=False)
    op.create_foreign_key('blog_products_blog_id_fkey', 'post_products', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_blog_products_symbol', 'post_products', ['product_symbol'], unique=False)
    op.create_index('idx_blog_products_blog_id', 'post_products', ['post_id'], unique=False)
    op.create_unique_constraint('blog_products_blog_id_product_symbol_key', 'post_products', ['post_id', 'product_symbol'])
    op.alter_column('post_products', 'product_symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('post_products', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('blog_comments_blog_id_fkey', 'post_comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_blog_comments_status', 'post_comments', ['status'], unique=False)
    op.create_index('idx_blog_comments_created_at', 'post_comments', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_blog_comments_blog_id', 'post_comments', ['post_id'], unique=False)
    op.alter_column('post_comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('blog_charts_blog_id_fkey', 'post_charts', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_blog_charts_symbol', 'post_charts', ['symbol'], unique=False)
    op.create_index('idx_blog_charts_blog_id', 'post_charts', ['post_id'], unique=False)
    op.alter_column('post_charts', 'indicators',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('post_charts', 'symbols',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('post_charts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_blog_categories_slug', 'post_categories', ['slug'], unique=False)
    op.create_index('idx_blog_categories_parent', 'post_categories', ['parent_id'], unique=False)
    op.alter_column('onchain_metrics_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('onchain_metrics_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('onchain_metrics_info', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('ohlcv_intraday_data', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('ohlcv_intraday_data', sa.Column('adjusted_close', sa.NUMERIC(precision=24, scale=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ohlcv_intraday_data_timestamp_utc'), table_name='ohlcv_intraday_data')
    op.drop_index(op.f('ix_ohlcv_intraday_data_ohlcv_id'), table_name='ohlcv_intraday_data')
    op.drop_index(op.f('ix_ohlcv_intraday_data_asset_id'), table_name='ohlcv_intraday_data')
    op.create_unique_constraint('uq_ohlcv_intraday_data', 'ohlcv_intraday_data', ['asset_id', 'timestamp_utc', 'data_interval'])
    op.create_index('idx_ohlcv_intraday_timestamp', 'ohlcv_intraday_data', ['timestamp_utc'], unique=False)
    op.create_index('idx_ohlcv_intraday_asset_date', 'ohlcv_intraday_data', ['asset_id', 'timestamp_utc'], unique=False)
    op.create_index('idx_ohlcv_intraday_asset', 'ohlcv_intraday_data', ['asset_id'], unique=False)
    op.alter_column('ohlcv_intraday_data', 'change_percent',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=sa.NUMERIC(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('ohlcv_intraday_data', 'volume',
               existing_type=sa.DECIMAL(precision=30, scale=10),
               type_=sa.BIGINT(),
               nullable=True)
    op.add_column('ohlcv_day_data', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('ohlcv_day_data', sa.Column('adjusted_close', sa.NUMERIC(precision=24, scale=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ohlcv_day_data_timestamp_utc'), table_name='ohlcv_day_data')
    op.drop_index(op.f('ix_ohlcv_day_data_ohlcv_id'), table_name='ohlcv_day_data')
    op.drop_index(op.f('ix_ohlcv_day_data_asset_id'), table_name='ohlcv_day_data')
    op.create_unique_constraint('uq_ohlcv_day_data', 'ohlcv_day_data', ['asset_id', 'timestamp_utc', 'data_interval'])
    op.create_index('uq_ohlcv_day_asset_time', 'ohlcv_day_data', ['asset_id', 'timestamp_utc'], unique=False)
    op.create_index('idx_ohlcv_day_timestamp', 'ohlcv_day_data', ['timestamp_utc'], unique=False)
    op.create_index('idx_ohlcv_day_asset_date', 'ohlcv_day_data', ['asset_id', 'timestamp_utc'], unique=False)
    op.create_index('idx_ohlcv_day_asset', 'ohlcv_day_data', ['asset_id'], unique=False)
    op.create_index('idx_ohlcv_asset_timestamp_desc', 'ohlcv_day_data', ['asset_id', sa.text('timestamp_utc DESC')], unique=False)
    op.alter_column('ohlcv_day_data', 'change_percent',
               existing_type=sa.DECIMAL(precision=10, scale=4),
               type_=sa.NUMERIC(precision=9, scale=4),
               existing_nullable=True)
    op.alter_column('ohlcv_day_data', 'volume',
               existing_type=sa.DECIMAL(precision=30, scale=10),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('ohlcv_day_data', 'data_interval',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint('uq_m2_data_timestamp', 'm2_data', type_='unique')
    op.drop_index(op.f('ix_m2_data_timestamp_utc'), table_name='m2_data')
    op.alter_column('m2_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('m2_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'index_infos', type_='foreignkey')
    op.drop_index(op.f('ix_index_infos_index_info_id'), table_name='index_infos')
    op.drop_column('index_infos', 'updated_at')
    op.drop_column('index_infos', 'created_at')
    op.drop_constraint(None, 'etf_info', type_='foreignkey')
    op.drop_index(op.f('ix_etf_info_etf_info_id'), table_name='etf_info')
    op.drop_index(op.f('ix_etf_info_asset_id'), table_name='etf_info')
    op.create_unique_constraint('unique_etf_info_asset_id', 'etf_info', ['asset_id'])
    op.create_index('idx_etf_info_asset_id', 'etf_info', ['asset_id'], unique=False)
    op.create_index('idx_etf_info_asset', 'etf_info', ['asset_id'], unique=False)
    op.alter_column('etf_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('etf_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('etf_info', 'holdings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='ETF 보유 종목 정보',
               existing_nullable=True)
    op.alter_column('etf_info', 'sectors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='ETF 섹터별 비중 정보',
               existing_nullable=True)
    op.alter_column('etf_info', 'leveraged',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Leveraged status',
               existing_nullable=True)
    op.alter_column('etf_info', 'inception_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Inception Date',
               existing_nullable=True)
    op.alter_column('etf_info', 'dividend_yield',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Dividend Yield',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'portfolio_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Portfolio Turnover Rate',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'net_expense_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Net Expense Ratio',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'net_assets',
               existing_type=sa.NUMERIC(precision=22, scale=0),
               comment=None,
               existing_comment='Net Assets',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('etf_info', 'snapshot_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Information reference date (stores the latest information)',
               existing_nullable=False)
    op.drop_constraint('uq_economic_indicator_code_timestamp', 'economic_indicators', type_='unique')
    op.drop_index(op.f('ix_economic_indicators_timestamp'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_indicator_code'), table_name='economic_indicators')
    op.alter_column('economic_indicators', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('economic_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('economic_indicators', 'value',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.alter_column('economic_indicators', 'indicator_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('economic_indicators', 'indicator_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'crypto_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_crypto_metrics_timestamp_utc'), table_name='crypto_metrics')
    op.drop_index(op.f('ix_crypto_metrics_asset_id'), table_name='crypto_metrics')
    op.drop_constraint('ux_crypto_metrics_asset_ts', 'crypto_metrics', type_='unique')
    op.create_index('ux_crypto_metrics_asset_ts', 'crypto_metrics', ['asset_id', 'timestamp_utc'], unique=False)
    op.alter_column('crypto_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crypto_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'crypto_data', type_='foreignkey')
    op.drop_index(op.f('ix_crypto_data_symbol'), table_name='crypto_data')
    op.drop_index(op.f('ix_crypto_data_id'), table_name='crypto_data')
    op.drop_index(op.f('ix_crypto_data_asset_id'), table_name='crypto_data')
    op.create_unique_constraint('unique_crypto_data_asset_id', 'crypto_data', ['asset_id'])
    op.create_index('idx_crypto_data_asset_id', 'crypto_data', ['asset_id'], unique=False)
    op.create_index('idx_crypto_data_asset', 'crypto_data', ['asset_id'], unique=False)
    op.alter_column('crypto_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crypto_data', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'bond_market_data', type_='foreignkey')
    op.alter_column('bond_market_data', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('fk_assets_asset_type', 'assets', 'asset_types', ['asset_type_id'], ['asset_type_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.create_unique_constraint('uq_assets_ticker', 'assets', ['ticker'])
    op.create_index('idx_assets_asset_type_id', 'assets', ['asset_type_id'], unique=False)
    op.create_index('idx_asset_basic_type', 'assets', ['asset_type_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_asset_basic_ticker', 'assets', ['ticker'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('assets', 'data_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'fmp'::character varying"))
    op.alter_column('assets', 'last_collections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('assets', 'collection_settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'asset_types', type_='unique')
    op.drop_index(op.f('ix_asset_types_asset_type_id'), table_name='asset_types')
    op.drop_index(op.f('ix_app_configurations_config_key'), table_name='app_configurations')
    op.alter_column('app_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_configurations', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_api_call_logs_created_at'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_asset_ticker'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_api_name'), table_name='api_call_logs')
    op.alter_column('api_call_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('api_call_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('menus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'static'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('menu_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], name='menus_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='menus_pkey')
    )
    op.create_index('ux_menus_path', 'menus', ['path'], unique=False)
    op.create_table('blog_post_tags',
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['posts.id'], name='blog_post_tags_blog_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['post_tags.id'], name='blog_post_tags_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id', name='blog_post_tags_pkey')
    )
    op.create_table('websocket_orchestrator_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('log_level', sa.VARCHAR(length=50), server_default=sa.text("'INFO'::character varying"), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False)
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False)
    )
    op.create_table('menu_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'static'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_info.id'], name='menu_info_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='menu_info_pkey')
    )
    # ### end Alembic commands ###
