"""add nrpl_usd and sth_realized_price

Revision ID: d8f15d289531
Revises: 3748057f2a75
Create Date: 2026-01-12 09:44:26.844523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f15d289531'
down_revision: Union[str, None] = '3748057f2a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_metrics', sa.Column('nrpl_usd', sa.DECIMAL(precision=24, scale=10), nullable=True))
    op.add_column('crypto_metrics', sa.Column('sth_realized_price', sa.DECIMAL(precision=24, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_metrics', 'sth_realized_price')
    op.drop_column('crypto_metrics', 'nrpl_usd')
    # ### end Alembic commands ###
